package com.zegocloud.uikit.prebuilt.call.config;

public enum ZegoMenuBarButtonName {
    TOGGLE_CAMERA_BUTTON,
    TOGGLE_MICROPHONE_BUTTON,
    SWITCH_AUDIO_OUTPUT_BUTTON,
    HANG_UP_BUTTON,
    SWITCH_CAMERA_BUTTON,
    SHOW_MEMBER_LIST_BUTTON,
    SCREEN_SHARING_TOGGLE_BUTTON,
    BEAUTY_BUTTON,
    CHAT_BUTTON
}
